"""
Run a pipeline from a JSON configuration.

This script uses ionworkspipeline to parse and execute the configuration
generated by ionworksschema. This represents the "cloud side" of the workflow.
"""

import json
from pathlib import Path

import matplotlib.pyplot as plt

from ionworkspipeline.parsers import parse_pipeline


def main():
    # Load config
    config_file = Path(__file__).parent / "config.json"
    print(f"Loading: {config_file}")

    with open(config_file) as f:
        config = json.load(f)

    # Parse into Pipeline
    print("Parsing configuration...")
    pipeline = parse_pipeline(config)
    print(f"  Components: {list(pipeline.elements.keys())}")

    # Run
    print("\nRunning pipeline...")
    print("=" * 60)
    results = pipeline.run()
    print("=" * 60)

    # Results
    print("\nFitted parameters:")
    for name, value in results.items():
        if isinstance(value, (int, float)):
            print(f"  {name}: {value:.6g}")

    # Plot
    component = pipeline.elements["cathode_ocp_fit"]
    callbacks = component.results.callbacks
    for cb_list in callbacks.values():
        fig_fit, _ = cb_list[0].plot_fit_results()

    fig_trace, _ = component.plot_trace()

    # Save
    output_dir = Path(__file__).parent
    fig_fit.savefig(output_dir / "fit_results.png", dpi=150)
    fig_trace.savefig(output_dir / "trace.png", dpi=150)
    print("\nSaved: fit_results.png, trace.png")

    plt.show()


if __name__ == "__main__":
    main()
